### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ynghr1226** [ynghr1226/protospace-32454#1]
#URL
https://protospace-32454.herokuapp.com/

**Comment by checker-ms** [comment]
柳原さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
ログアウト状態のユーザーは、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページ以外のページに遷移しようとすると、ログインページにリダイレクトされること

現状はトップページにリダイレクトされている状態です。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ynghr1226** [comment]
いただいた修正箇所訂正いたしました
ご確認お願い致します

**Comment by checker-ms** [comment]
柳原さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[現状]
ログアウト状態のユーザーが、編集ページに遷移しようとすると、トップページにリダイレクトされています。

[修正箇所]
ログアウト状態のユーザーが、編集ページに遷移しようとすると、ログインページにリダイレクトされる

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ynghr1226** [comment]
https://gyazo.com/4756e76b92bf6ebf08f0cef7da314b7f
すみません
こちらの挙動ですと上記のGIFの通り
ログアウト状態で編集ページに遷移後ログインページに遷移している状態なのですが、
リモートリポジトリに反映がなされていない状態でしょうか？
それともこちら修正後に再びリモートリポジトリにあげるだけではなくHerokuへ何かしらのプッシュが必要でしょうか？

**Comment by checker-ms** [comment]
柳原さん、ご質問ありがとうございます！
おっしゃる通りで、ご相談いただいたように「herokuを最新状態に更新する」必要があります！

下記カリキュラムを参考にしていただき、再度ご提出をいただけたらと思います。

https://master.tech-camp.in/curriculums/4804

**Comment by ynghr1226** [comment]
「herokuを最新状態に更新する」を修正いたしました
重ねて申し訳ないですがご確認のほど宜しくお願い致します

**Comment by checker-ms** [comment]
柳原さん、修正ありがとうございます！

挙動確認させていただいたところ、問題ありませんでしたので、LGTMとさせていただきます🎉

実装お疲れ様でした。おめでとうございます！
